# Generated by Django 4.2.4 on 2023-08-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='email@wma.com', max_length=255),
            preserve_default=False,
        ),
    ]
