# Generated by Django 4.2.4 on 2023-08-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_blog', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
