# Generated by Django 4.2.4 on 2023-08-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogadmin',
            name='passion',
            field=models.CharField(default='zembo', max_length=250),
            preserve_default=False,
        ),
    ]
